import type { HarnessTemplate } from '../harness-types'
import {
  BASE_FORBIDDEN_GLOBS,
  DEFAULT_ROLLBACK,
  HARNESS_MEMORY_GLOBS,
  initialStateFor,
  rulesFor
} from './common'

const DEPENDENCY_FORBIDDEN = [
  'package.json',
  'package-lock.json',
  'pnpm-lock.yaml',
  'yarn.lock',
  'Cargo.toml',
  'Cargo.lock',
  'pyproject.toml',
  'poetry.lock',
  'uv.lock',
  'requirements*.txt',
  'go.mod',
  'go.sum',
  'bun.lock',
  'bun.lockb'
] as const

const TEST_GLOBS = [
  'test/**',
  'tests/**',
  '**/test/**',
  '**/tests/**',
  '**/__tests__/**',
  '**/*.test.*',
  '**/*.spec.*',
  '**/*_test.go',
  '**/test_*.py'
] as const

const CODE_AND_TEST_GLOBS = [
  'src/**',
  'app/**',
  'lib/**',
  'packages/**',
  'crates/**',
  'cmd/**',
  'internal/**',
  'pkg/**',
  ...TEST_GLOBS
] as const

const PACKAGE_TEST_SCRIPT_PREFLIGHT = [
  'package_test_script_ready() {',
  '  command -v node >/dev/null 2>&1 || { echo "node is required to inspect package.json test configuration" >&2; return 2; }',
  `  node -e 'const p=require("./package.json"); const t=p.scripts&&p.scripts.test; process.exit(typeof t==="string" && t.trim().length>0 && !/no test specified/i.test(t) ? 0 : 1)' >/dev/null 2>&1 || { echo "package.json has no real, non-empty scripts.test command" >&2; return 2; }`,
  '}'
].join('\n')

/**
 * A portable best-effort repository gate. It prefers an explicit Make test
 * target, then detects common JavaScript, Rust, Go, and Python project roots.
 * Unsupported workspaces fail closed instead of turning a missing `npm` setup
 * into false evidence.
 */
const REPOSITORY_TEST_RUNNER = [
  PACKAGE_TEST_SCRIPT_PREFLIGHT,
  'run_repository_tests() {',
  "  if [ -f Makefile ] && grep -Eq '^[[:space:]]*test[[:space:]]*:' Makefile; then",
  '    command -v make >/dev/null 2>&1 || { echo "make is required by this repository" >&2; return 2; }',
  '    make test',
  '  elif [ -f package.json ]; then',
  '    if [ -f pnpm-lock.yaml ]; then',
  '      package_test_script_ready || return $?',
  '      command -v pnpm >/dev/null 2>&1 || { echo "pnpm-lock.yaml exists but pnpm is unavailable" >&2; return 2; }',
  '      pnpm test',
  '    elif [ -f yarn.lock ]; then',
  '      package_test_script_ready || return $?',
  '      command -v yarn >/dev/null 2>&1 || { echo "yarn.lock exists but yarn is unavailable" >&2; return 2; }',
  '      yarn test',
  '    elif [ -f bun.lock ] || [ -f bun.lockb ]; then',
  '      command -v bun >/dev/null 2>&1 || { echo "a Bun lockfile exists but bun is unavailable" >&2; return 2; }',
  '      bun test',
  '    else',
  '      package_test_script_ready || return $?',
  '      command -v npm >/dev/null 2>&1 || { echo "package.json exists but npm is unavailable" >&2; return 2; }',
  '      npm test',
  '    fi',
  '  elif [ -f Cargo.toml ]; then',
  '    command -v cargo >/dev/null 2>&1 || { echo "Cargo.toml exists but cargo is unavailable" >&2; return 2; }',
  '    cargo test',
  '  elif [ -f go.mod ]; then',
  '    command -v go >/dev/null 2>&1 || { echo "go.mod exists but go is unavailable" >&2; return 2; }',
  '    go test ./...',
  '  elif [ -f pyproject.toml ] || [ -f pytest.ini ] || [ -f setup.cfg ]; then',
  '    if [ -f uv.lock ] && command -v uv >/dev/null 2>&1; then',
  `      uv run python -c 'import pytest' >/dev/null 2>&1 || { echo "pytest is unavailable in the uv environment" >&2; return 2; }`,
  '      uv run pytest',
  '    else',
  '      command -v python3 >/dev/null 2>&1 || { echo "Python test configuration exists but python3 is unavailable" >&2; return 2; }',
  `      python3 -c 'import pytest' >/dev/null 2>&1 || { echo "pytest is unavailable for python3" >&2; return 2; }`,
  '      python3 -m pytest',
  '    fi',
  '  else',
  '    echo "No supported repository test gate found; configure a blank harness with the repo-native verifier." >&2',
  '    return 2',
  '  fi',
  '}'
].join('\n')

const BUG_CHANGE_GUARD = [
  'collect_changed_paths() {',
  '  _collect_out=$1',
  '  shift',
  '  : > "$_collect_out" || return 2',
  '  git diff --no-renames --name-only -- "$@" > "$_collect_out" || return 2',
  '  git diff --cached --no-renames --name-only -- "$@" >> "$_collect_out" || return 2',
  '  git ls-files --others --exclude-standard -- "$@" >> "$_collect_out" || return 2',
  '  LC_ALL=C sort -u "$_collect_out"',
  '}',
  'assert_only_changed_test() {',
  '  _allowed_test=$1',
  '  _guard_tmp=$2',
  '  _all_changes=$(collect_changed_paths "$_guard_tmp") || return 2',
  '  : > "$_guard_tmp" || return 2',
  '  while IFS= read -r _changed; do',
  '    [ -n "$_changed" ] || continue',
  '    [ "$_changed" = "$_allowed_test" ] && continue',
  '    case "$_changed" in',
  '      "$_harness_rel/"*) continue ;;',
  '    esac',
  '    printf "%s\\n" "$_changed" >> "$_guard_tmp" || return 2',
  '  done <<EOF',
  '$_all_changes',
  'EOF',
  '  if [ -s "$_guard_tmp" ]; then',
  '    echo "Bug reproducer must change exactly one test and no other workspace file outside its own harness directory:" >&2',
  '    cat "$_guard_tmp" >&2',
  '    return 1',
  '  fi',
  '  return 0',
  '}',
  'assert_unique_substring_target() {',
  '  _exact_test=$1',
  '  _target_tmp=$2',
  '  git ls-files --cached --others --exclude-standard > "$_target_tmp" || return 2',
  '  while IFS= read -r _candidate; do',
  '    [ -n "$_candidate" ] || continue',
  '    [ "$_candidate" = "$_exact_test" ] && continue',
  '    case "$_candidate" in',
  '      *"$_exact_test"*)',
  '        echo "The selected runner cannot isolate the changed test path exactly; it also matches $_candidate." >&2',
  '        return 2',
  '        ;;',
  '    esac',
  '  done < "$_target_tmp"',
  '  return 0',
  '}',
  'collect_process_tree() {',
  '  for _child_pid in $(pgrep -P "$1" 2>/dev/null || :); do',
  '    collect_process_tree "$_child_pid"',
  '  done',
  '  printf "%s\\n" "$1"',
  '}',
  'terminate_process_tree() {',
  '  _process_tree=$(collect_process_tree "$1") || return 2',
  '  for _kill_pid in $_process_tree; do',
  '    kill -TERM "$_kill_pid" 2>/dev/null || :',
  '  done',
  '  sleep 1 </dev/null >/dev/null 2>&1',
  '  for _kill_pid in $_process_tree; do',
  '    kill -KILL "$_kill_pid" 2>/dev/null || :',
  '  done',
  '  return 0',
  '}'
].join('\n')

const PACKAGE_TARGETED_TEST_SCRIPT_PREFLIGHT = [
  'package_test_runner_kind() {',
  `  node -e 'const p=require("./package.json"); const raw=p.scripts&&p.scripts.test; const t=typeof raw==="string"?raw.trim():""; const m=t.match(/^(vitest(?:[ ]+run)?|jest|node[ ]+--test|tsx[ ]+--test|mocha|ava)(?:[ ]+(.*))?$/); const runner=m?.[1]??""; const args=m?.[2]?m[2].trim().split(/[ ]+/):[]; const safeFlag=/^(?:--run|--runInBand|--silent|--verbose|--no-color|--no-coverage|--coverage(?:=.*)?|--bail(?:=.*)?|--config=.*|--environment=.*|--maxWorkers=.*|--pool=.*|--no-file-parallelism)$/; const runOnce=!runner.startsWith("vitest")||runner==="vitest run"||args.includes("--run"); const targetable=!!m&&runOnce&&args.every((arg)=>safeFlag.test(arg)); const simple=!/[;&|\`$()<>\\r\\n]/.test(t); if(!(targetable&&simple))process.exit(1); const kind=runner.startsWith("vitest")?"vitest":runner==="node --test"?"node":runner==="tsx --test"?"tsx":runner; process.stdout.write(kind)' 2>/dev/null || { echo "package.json scripts.test cannot target one changed test file safely in one-shot mode; configure a blank harness with the repo-native focused command" >&2; return 2; }`,
  '}'
].join('\n')

/**
 * Run exactly the one changed regression test. Whole-suite failure is not
 * evidence: a pre-existing failure elsewhere must never make this gate green.
 * Unsupported/custom runners fail closed and direct the operator to a blank
 * harness with an explicit focused verifier.
 */
const TARGETED_CHANGED_TEST_RUNNER = [
  'run_changed_test() {',
  '  _changed_test=$1',
  '  case "$_changed_test" in',
  '    *.js|*.cjs|*.mjs|*.jsx|*.ts|*.tsx)',
  '      [ -f package.json ] || { echo "A JavaScript/TypeScript changed test requires package.json." >&2; return 2; }',
  '      if [ -f bun.lock ] || [ -f bun.lockb ]; then',
  '        assert_unique_substring_target "$_changed_test" "$_changes_tmp" || return $?',
  '        printf "%s\\n" bun > "$_runner_kind_file" || return 2',
  '        command -v bun >/dev/null 2>&1 || { echo "A Bun lockfile exists but bun is unavailable." >&2; return 2; }',
  '        bun test "$_changed_test"',
  '      elif [ -f pnpm-lock.yaml ]; then',
  '        package_test_script_ready || return $?',
  '        _package_runner=$(package_test_runner_kind) || return $?',
  '        [ "$_package_runner" != vitest ] || assert_unique_substring_target "$_changed_test" "$_changes_tmp" || return $?',
  '        printf "%s\\n" "$_package_runner" > "$_runner_kind_file" || return 2',
  '        command -v pnpm >/dev/null 2>&1 || { echo "pnpm-lock.yaml exists but pnpm is unavailable." >&2; return 2; }',
  '        if [ "$_package_runner" = jest ]; then pnpm test --runTestsByPath "$_changed_test"; else pnpm test "$_changed_test"; fi',
  '      elif [ -f yarn.lock ]; then',
  '        package_test_script_ready || return $?',
  '        _package_runner=$(package_test_runner_kind) || return $?',
  '        [ "$_package_runner" != vitest ] || assert_unique_substring_target "$_changed_test" "$_changes_tmp" || return $?',
  '        printf "%s\\n" "$_package_runner" > "$_runner_kind_file" || return 2',
  '        command -v yarn >/dev/null 2>&1 || { echo "yarn.lock exists but yarn is unavailable." >&2; return 2; }',
  '        if [ "$_package_runner" = jest ]; then yarn test --runTestsByPath "$_changed_test"; else yarn test "$_changed_test"; fi',
  '      else',
  '        package_test_script_ready || return $?',
  '        _package_runner=$(package_test_runner_kind) || return $?',
  '        [ "$_package_runner" != vitest ] || assert_unique_substring_target "$_changed_test" "$_changes_tmp" || return $?',
  '        printf "%s\\n" "$_package_runner" > "$_runner_kind_file" || return 2',
  '        command -v npm >/dev/null 2>&1 || { echo "package.json exists but npm is unavailable." >&2; return 2; }',
  '        if [ "$_package_runner" = jest ]; then npm test -- --runTestsByPath "$_changed_test"; else npm test -- "$_changed_test"; fi',
  '      fi',
  '      ;;',
  '    *.py)',
  '      printf "%s\\n" pytest > "$_runner_kind_file" || return 2',
  '      if [ -f uv.lock ]; then',
  '        command -v uv >/dev/null 2>&1 || { echo "uv.lock exists but uv is unavailable." >&2; return 2; }',
  `        uv run python -c 'import pytest' >/dev/null 2>&1 || { echo "pytest is unavailable in the uv environment." >&2; return 2; }`,
  '        uv run pytest "$_changed_test"',
  '      else',
  '        command -v python3 >/dev/null 2>&1 || { echo "A Python changed test requires python3." >&2; return 2; }',
  `        python3 -c 'import pytest' >/dev/null 2>&1 || { echo "pytest is unavailable for python3." >&2; return 2; }`,
  '        python3 -m pytest "$_changed_test"',
  '      fi',
  '      ;;',
  '    *.go)',
  '      printf "%s\\n" go > "$_runner_kind_file" || return 2',
  '      command -v go >/dev/null 2>&1 || { echo "A Go changed test requires go." >&2; return 2; }',
  '      case "$_changed_test" in *_test.go) ;; *) echo "The changed Go file is not a *_test.go test." >&2; return 2 ;; esac',
  '      _go_dir=$(dirname -- "$_changed_test")',
  `      _go_test_pkg=$(sed -n 's/^[[:space:]]*package[[:space:]][[:space:]]*\\([[:alnum:]_][[:alnum:]_]*\\).*/\\1/p' "$_changed_test" | head -n 1)`,
  '      set -- "$_changed_test"',
  '      _go_product_pkg=',
  '      for _go_file in "$_go_dir"/*.go; do',
  '        [ -e "$_go_file" ] || continue',
  '        [ "$_go_file" = "$_changed_test" ] && continue',
  '        case "$_go_file" in *_test.go) continue ;; esac',
  `        [ -n "$_go_product_pkg" ] || _go_product_pkg=$(sed -n 's/^[[:space:]]*package[[:space:]][[:space:]]*\\([[:alnum:]_][[:alnum:]_]*\\).*/\\1/p' "$_go_file" | head -n 1)`,
  '        set -- "$@" "$_go_file"',
  '      done',
  '      [ -z "$_go_product_pkg" ] || [ "$_go_test_pkg" = "$_go_product_pkg" ] || { echo "An external-package Go test cannot be isolated safely by this generic gate." >&2; return 2; }',
  '      go test "$@"',
  '      ;;',
  '    *.rs)',
  '      printf "%s\\n" rust > "$_runner_kind_file" || return 2',
  '      command -v cargo >/dev/null 2>&1 || { echo "A Rust changed test requires cargo." >&2; return 2; }',
  '      case "$_changed_test" in tests/*.rs|*/tests/*.rs) ;; *) echo "Only Rust integration-test targets under tests/ can be isolated safely." >&2; return 2 ;; esac',
  '      _manifest_dir=$(dirname -- "$_changed_test")',
  '      _manifest_path=',
  '      while :; do',
  '        if [ -f "$_manifest_dir/Cargo.toml" ]; then _manifest_path="$_manifest_dir/Cargo.toml"; break; fi',
  '        [ "$_manifest_dir" = "." ] || [ "$_manifest_dir" = "/" ] && break',
  '        _manifest_dir=$(dirname -- "$_manifest_dir")',
  '      done',
  '      [ -n "$_manifest_path" ] || { echo "No Cargo.toml owns the changed integration test." >&2; return 2; }',
  '      _rust_target=$(basename -- "$_changed_test" .rs)',
  '      cargo test --manifest-path "$_manifest_path" --test "$_rust_target"',
  '      ;;',
  '    *)',
  '      echo "No supported file-targeted runner exists for the changed test; configure a blank harness with the repo-native focused command." >&2',
  '      return 2',
  '      ;;',
  '  esac',
  '}'
].join('\n')

function passingRepositoryGate(requireImplementationChange = false): string {
  const lines = ['#!/bin/sh', 'set -eu', 'cd "$(dirname "$0")/../../.."', REPOSITORY_TEST_RUNNER]
  if (requireImplementationChange) {
    lines.push(
      'changed_work=$(git status --porcelain --untracked-files=all -- src app lib packages crates cmd internal pkg test tests migrations db docs \\',
      "  ':(glob)**/__tests__/**' ':(glob)**/*.test.*' ':(glob)**/*.spec.*')",
      'if [ -z "$changed_work" ]; then',
      '  echo "Expected at least one changed implementation, test, migration, or documentation file." >&2',
      '  exit 1',
      'fi'
    )
  }
  lines.push('run_repository_tests', '')
  return lines.join('\n')
}

function failingRepositoryGate(): string {
  return [
    '#!/bin/sh',
    'set -u',
    '_script_dir=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd -P) || { echo "Could not resolve the harness directory." >&2; exit 2; }',
    '_repo_root=$(CDPATH= cd -- "$_script_dir/../../.." && pwd -P) || { echo "Could not resolve the repository root." >&2; exit 2; }',
    'cd "$_repo_root" || { echo "Could not enter the repository root." >&2; exit 2; }',
    'case "$_script_dir/" in',
    '  "$_repo_root/"*) _harness_rel=${_script_dir#"$_repo_root/"} ;;',
    '  *) echo "Harness directory is outside the repository root." >&2; exit 2 ;;',
    'esac',
    '_verify_tmp=$(mktemp -d "${TMPDIR:-/tmp}/machina-bug-reproducer.XXXXXX") || exit 2',
    '_changes_tmp="$_verify_tmp/changes"',
    '_index_before="$_verify_tmp/index-before"',
    '_index_after="$_verify_tmp/index-after"',
    '_runner_kind_file="$_verify_tmp/runner-kind"',
    'output_file="$_verify_tmp/output"',
    'timeout_marker="$_verify_tmp/timed-out"',
    'trap \'rm -f "$_changes_tmp" "$_index_before" "$_index_after" "$_runner_kind_file" "$output_file" "$timeout_marker"; rmdir "$_verify_tmp" 2>/dev/null || :\' EXIT HUP INT TERM',
    BUG_CHANGE_GUARD,
    'if ! changed_tests=$(collect_changed_paths "$_changes_tmp" test tests \\',
    "  ':(glob)**/test/**' ':(glob)**/tests/**' ':(glob)**/__tests__/**' ':(glob)**/*.test.*' ':(glob)**/*.spec.*' ':(glob)**/*_test.go' ':(glob)**/test_*.py'); then",
    '  echo "Could not inspect changed test files; this is not bug evidence." >&2',
    '  exit 2',
    'fi',
    'if [ -z "$changed_tests" ]; then',
    '  echo "Expected at least one changed or untracked test file." >&2',
    '  exit 1',
    'fi',
    "changed_test_count=$(printf '%s\\n' \"$changed_tests\" | awk 'NF { count += 1 } END { print count + 0 }')",
    'if [ "$changed_test_count" -ne 1 ]; then',
    '  echo "Expected exactly one changed test file; found $changed_test_count." >&2',
    '  exit 1',
    'fi',
    `changed_test=$(printf '%s\n' "$changed_tests" | sed -n '1p')`,
    '[ -f "$changed_test" ] && [ ! -L "$changed_test" ] || { echo "The one changed test must be a present regular file, not a deletion or symlink." >&2; exit 1; }',
    'assert_only_changed_test "$changed_test" "$_changes_tmp"',
    '_guard_status=$?',
    'if [ "$_guard_status" -eq 2 ]; then',
    '  echo "Could not inspect the complete working tree; this is not bug evidence." >&2',
    '  exit 2',
    'fi',
    'if [ "$_guard_status" -ne 0 ]; then',
    '  exit 1',
    'fi',
    '_head_before=$(git rev-parse --verify HEAD) || { echo "Could not snapshot HEAD before the focused test." >&2; exit 2; }',
    'git ls-files --stage > "$_index_before" || { echo "Could not snapshot the Git index before the focused test." >&2; exit 2; }',
    '_test_hash_before=$(git hash-object -- "$changed_test") || { echo "Could not hash the changed test before execution." >&2; exit 2; }',
    PACKAGE_TEST_SCRIPT_PREFLIGHT,
    PACKAGE_TARGETED_TEST_SCRIPT_PREFLIGHT,
    TARGETED_CHANGED_TEST_RUNNER,
    'command -v pgrep >/dev/null 2>&1 || { echo "pgrep is required to contain a timed-out test process tree." >&2; exit 2; }',
    ': > "$timeout_marker"',
    'run_changed_test "$changed_test" >"$output_file" 2>&1 &',
    '_test_pid=$!',
    '(',
    '  _elapsed=0',
    '  while [ "$_elapsed" -lt 120 ] && kill -0 "$_test_pid" 2>/dev/null; do',
    '    sleep 1 </dev/null >/dev/null 2>&1',
    '    _elapsed=$((_elapsed + 1))',
    '  done',
    '  if kill -0 "$_test_pid" 2>/dev/null; then',
    '    printf "%s\\n" timeout > "$timeout_marker"',
    '    terminate_process_tree "$_test_pid" || :',
    '  fi',
    ') &',
    '_watchdog_pid=$!',
    'wait "$_test_pid"',
    'status=$?',
    'if [ -s "$timeout_marker" ]; then',
    '  wait "$_watchdog_pid" 2>/dev/null || :',
    'else',
    '  kill "$_watchdog_pid" 2>/dev/null || :',
    '  wait "$_watchdog_pid" 2>/dev/null || :',
    'fi',
    'cat "$output_file"',
    'if [ -s "$timeout_marker" ]; then',
    '  echo "The focused test command exceeded 120 seconds; this is not bug evidence." >&2',
    '  exit 1',
    'fi',
    '_head_after=$(git rev-parse --verify HEAD) || { echo "Could not inspect HEAD after the focused test." >&2; exit 2; }',
    'git ls-files --stage > "$_index_after" || { echo "Could not inspect the Git index after the focused test." >&2; exit 2; }',
    'if [ "$_head_after" != "$_head_before" ] || ! cmp -s "$_index_before" "$_index_after"; then',
    '  echo "The workspace changed while the focused test was running (HEAD or index changed)." >&2',
    '  exit 1',
    'fi',
    '[ -f "$changed_test" ] && [ ! -L "$changed_test" ] || { echo "The changed test disappeared or became a symlink while it was running." >&2; exit 1; }',
    '_test_hash_after=$(git hash-object -- "$changed_test") || { echo "Could not hash the changed test after execution." >&2; exit 2; }',
    'if [ "$_test_hash_after" != "$_test_hash_before" ]; then',
    '  echo "The changed test rewrote itself while it was running; this is not stable bug evidence." >&2',
    '  exit 1',
    'fi',
    'assert_only_changed_test "$changed_test" "$_changes_tmp"',
    '_post_guard_status=$?',
    'if [ "$_post_guard_status" -eq 2 ]; then',
    '  echo "Could not inspect the workspace after the focused test; this is not bug evidence." >&2',
    '  exit 2',
    'fi',
    'if [ "$_post_guard_status" -ne 0 ]; then',
    '  echo "The workspace changed while the focused test was running." >&2',
    '  exit 1',
    'fi',
    'if [ "$status" -eq 0 ]; then',
    '  echo "The changed test passed; it does not reproduce the reported bug." >&2',
    '  exit 1',
    'fi',
    'if [ "$status" -eq 2 ] || [ "$status" -eq 126 ] || [ "$status" -eq 127 ]; then',
    '  echo "The test command could not run; this is not bug evidence." >&2',
    '  exit 1',
    'fi',
    'if grep -Eiq \'no tests? (found|collected)|no test files found|missing script|no test specified|command not found|cannot find module|no module named|modulenotfounderror|pytest is unavailable|failed to resolve|no such file or directory|unknown file extension|syntax[[:space:]]*error|setup failed|failed to load (config|configuration)|error: failed to|error during build|build failed|compilation failed|could not compile|build script\' "$output_file"; then',
    '  echo "The observed failure is test discovery or infrastructure, not accepted bug evidence." >&2',
    '  exit 1',
    'fi',
    '_runner_kind=$(cat "$_runner_kind_file" 2>/dev/null) || { echo "The focused runner did not identify itself; this is not bug evidence." >&2; exit 1; }',
    'case "$_runner_kind" in',
    '  node|tsx)',
    '    _node_executed=false',
    '    if grep -Eq \'^# Subtest: .+\' "$output_file" && grep -Eq \'^not ok [0-9]+ - .+\' "$output_file"; then',
    '      _node_executed=true',
    '    fi',
    '    if grep -Eq \'tests[[:space:]]+[1-9][0-9]*\' "$output_file" && grep -Eq \'fail[[:space:]]+[1-9][0-9]*\' "$output_file" && grep -F -- "test at $changed_test:" "$output_file" >/dev/null 2>&1; then',
    '      _node_executed=true',
    '    fi',
    '    if [ "$_node_executed" != true ]; then',
    '      echo "The JavaScript test body did not execute and fail; suite-load errors are not bug evidence." >&2',
    '      exit 1',
    '    fi',
    '    if grep -F -- "# Subtest: $_repo_root/$changed_test" "$output_file" >/dev/null 2>&1; then',
    '      echo "The JavaScript file failed to load before a test body executed." >&2',
    '      exit 1',
    '    fi',
    '    ;;',
    '  jest)',
    '    if ! grep -Eq \'Tests:[[:space:]]+.*[1-9][0-9]* failed\' "$output_file"; then',
    '      echo "The JavaScript test body did not execute and fail; suite-load errors are not bug evidence." >&2',
    '      exit 1',
    '    fi',
    '    ;;',
    '  vitest)',
    '    if ! grep -Eq \'Tests[[:space:]]+[1-9][0-9]* failed\' "$output_file"; then',
    '      echo "The JavaScript test body did not execute and fail; suite-load errors are not bug evidence." >&2',
    '      exit 1',
    '    fi',
    '    ;;',
    '  mocha)',
    '    if ! grep -Eq \'[1-9][0-9]* failing\' "$output_file" || grep -Eiq \'(before|after)( all| each)? hook\' "$output_file"; then',
    '      echo "The JavaScript test body did not execute and fail; hook errors are not bug evidence." >&2',
    '      exit 1',
    '    fi',
    '    ;;',
    '  ava)',
    '    if ! grep -Eiq \'[1-9][0-9]* tests? failed\' "$output_file"; then',
    '      echo "The JavaScript test body did not execute and fail; hook and load errors are not bug evidence." >&2',
    '      exit 1',
    '    fi',
    '    ;;',
    '  bun)',
    '    if ! grep -Eq \'\\(fail\\)[[:space:]]+\' "$output_file"; then',
    '      echo "The Bun test body did not execute and fail; load errors are not bug evidence." >&2',
    '      exit 1',
    '    fi',
    '    ;;',
    '  pytest)',
    '    if ! grep -F -- "FAILED $changed_test::" "$output_file" >/dev/null 2>&1; then',
    '      echo "The Python test body did not execute and fail; setup, collection, and load errors are not bug evidence." >&2',
    '      exit 1',
    '    fi',
    '    ;;',
    '  go)',
    '    if ! grep -Eq -- \'--- FAIL: .+\' "$output_file"; then',
    '      echo "The Go test body did not execute and fail; setup and build errors are not bug evidence." >&2',
    '      exit 1',
    '    fi',
    '    ;;',
    '  rust)',
    '    if ! grep -Eq \'test .+ \\.\\.\\. FAILED\' "$output_file"; then',
    '      echo "The Rust test body did not execute and fail; setup and build errors are not bug evidence." >&2',
    '      exit 1',
    '    fi',
    '    ;;',
    '  *)',
    '    echo "No runner-specific executed-test evidence contract exists for $_runner_kind." >&2',
    '    exit 1',
    '    ;;',
    'esac',
    'echo "The one changed test produced an executable assertion/failure."',
    'echo "The operator must still confirm that the failure matches the requested defect."',
    ''
  ].join('\n')
}

const BUG_REPRODUCER: HarnessTemplate = {
  id: 'bug-reproducer',
  label: 'Bug reproducer',
  category: 'Engineering',
  audience: ['seasoned-programmer'],
  description: 'Captures one minimal failing test for a reported defect without fixing it.',
  adapter: 'codex',
  permissionMode: 'queue-all-writes',
  budgets: { maxTurns: 6, maxWritesPerMinute: 6 },
  requiresConfiguration: false,
  skillBody: [
    'Turn one reported bug into one minimal failing regression test, then stop.',
    '',
    '1. Ask for the defect, expected behavior, and any known reproduction command.',
    '2. Run the repository test gate and inspect the working tree before editing. If tests are already red, the runner is unsupported, or unrelated changes are present, report the blocker and stop.',
    '3. Reproduce the behavior without changing product code and add exactly one focused test under the existing test layout.',
    '4. Run the narrowest available test command and confirm its assertion fails for the requested reason.',
    '5. Do not fix the bug. Run the verification gate, quote the matching failure evidence, and stop.'
  ].join('\n'),
  rules: rulesFor(
    '- [critical] Never edit product source while producing the reproducer.',
    '- [major] Add one failing test only and confirm its targeted assertion or runner failure.',
    '- [major] A missing runner, dirty unrelated file, discovery/setup error, or pre-existing failure is a blocker, not a successful reproduction.'
  ),
  scope: {
    goal: 'Prove one reported bug with one minimal failing regression test.',
    allowedGlobs: [...TEST_GLOBS, ...HARNESS_MEMORY_GLOBS],
    forbiddenGlobs: [...BASE_FORBIDDEN_GLOBS, ...DEPENDENCY_FORBIDDEN],
    acceptance:
      'Exactly one focused test is the only repository change and fails for the reported reason.',
    rollback: DEFAULT_ROLLBACK
  },
  verifySh: failingRepositoryGate(),
  initialState: initialStateFor('bug reproduction')
}

const TEST_FIXER: HarnessTemplate = {
  id: 'test-fixer',
  label: 'Test fixer',
  category: 'Engineering',
  audience: ['seasoned-programmer'],
  description: 'Runs the test suite, fixes the first failure, stops.',
  adapter: 'claude',
  permissionMode: 'queue-all-writes',
  budgets: { maxTurns: 10, maxWritesPerMinute: 10 },
  requiresConfiguration: false,
  skillBody: [
    'Fix exactly one failing test, verify the fix, and stop.',
    '',
    '1. Run the repository test gate (`sh <dir>/verify.sh`) and read the output.',
    '2. If every test passes, report "all tests passing" and stop — do not invent work.',
    '3. Identify the FIRST failing test in the output. Ignore the rest for this run.',
    '4. Read the failing test and the code under test. Diagnose the root cause before editing.',
    '5. Make the smallest change that fixes the root cause. Fix the code under test unless the test itself is provably wrong; say which you changed and why.',
    '6. Run the verification gate and report its full output.',
    '7. Summarize the failure, root cause, fix, and verification result. Then stop.'
  ].join('\n'),
  rules: rulesFor(
    '- [major] Fix one failing test per run and do not refactor beyond its root cause.',
    '- [major] Do not add, remove, or upgrade dependencies.',
    '- [minor] Do not reformat code you did not change.'
  ),
  scope: {
    goal: 'Make the failing test pass without breaking any other test.',
    allowedGlobs: [...CODE_AND_TEST_GLOBS, ...HARNESS_MEMORY_GLOBS],
    forbiddenGlobs: [...BASE_FORBIDDEN_GLOBS, ...DEPENDENCY_FORBIDDEN],
    acceptance: 'verify.sh exits 0 and the full test suite passes.',
    rollback: DEFAULT_ROLLBACK
  },
  verifySh: passingRepositoryGate(),
  initialState: initialStateFor('test-fixer')
}

const VERTICAL_SLICE_BUILDER: HarnessTemplate = {
  id: 'vertical-slice-builder',
  label: 'Vertical slice builder',
  category: 'Engineering',
  audience: ['seasoned-programmer'],
  description: 'Implements one acceptance-tested feature slice without unrelated refactoring.',
  adapter: 'codex',
  permissionMode: 'queue-all-writes',
  budgets: { maxTurns: 12, maxWritesPerMinute: 10 },
  requiresConfiguration: false,
  skillBody: [
    'Implement one narrow vertical slice from interface to behavior and tests.',
    '',
    '1. Restate the single acceptance outcome and locate the existing extension seams.',
    '2. Add or update the failing test that proves the outcome.',
    '3. Implement the smallest end-to-end change through existing patterns.',
    '4. Avoid dependency changes, opportunistic refactors, and adjacent features.',
    '5. Run the verification gate, summarize the slice and residuals, and stop.'
  ].join('\n'),
  rules: rulesFor(
    '- [major] Deliver one acceptance slice only; every changed line must support it.',
    '- [major] Do not add, remove, or upgrade dependencies.',
    '- [major] Preserve existing process, persistence, and trust boundaries.'
  ),
  scope: {
    goal: 'Implement one reviewable, acceptance-tested feature slice.',
    allowedGlobs: [
      ...CODE_AND_TEST_GLOBS,
      'migrations/**',
      'db/**',
      'docs/**',
      ...HARNESS_MEMORY_GLOBS
    ],
    forbiddenGlobs: [...BASE_FORBIDDEN_GLOBS, ...DEPENDENCY_FORBIDDEN],
    acceptance: 'The named acceptance test and repository checks pass with no unrelated changes.',
    rollback: DEFAULT_ROLLBACK
  },
  verifySh: passingRepositoryGate(true),
  initialState: initialStateFor('vertical-slice')
}

export const ENGINEERING_TEMPLATES = [BUG_REPRODUCER, TEST_FIXER, VERTICAL_SLICE_BUILDER] as const
